### ISSUE TITLE
Missing solutions! Unacceptable!

### ISSUE THREAD

**Issue by hexecute** [joshcai/24#1]
I was at a wild, raging penthouse party where we were playing 24 when someone suggested "13 13 11 1" as a possible puzzle. I was using joshcai.com/24 to ~~cheat~~ double-check my work and impress the ladies. I used the so-called "24 solver" and confidently announced that  "13 * (1 + 11 / 13)" was the only solution. To my surprise and horror, someone called me out with another easier solution of "(13-1)*(13-11)"! Everyone began pointing and laughing at me! I was humiliated and fled the party in tears! As a paying customer, this is COMPLETELY UNACCEPTABLE! I expect this to be fixed within 24 hours or I will call my bank and issue a chargeback!! **DO NOT TEST ME!!!**

**Comment by joshcai** [comment]
Hello @hexecute, thank you for reporting this severe issue, and I sincerely apologize for your humiliation at the penthouse party. This issue is now fixed (https://joshcai.com/24/?a=13&b=13&c=11&d=1&target=24). Unfortunately, I could not meet the 24 hour target, but I did fix it within 24 days at least.
